query GetVehicles($partner: Bytes) {
  vehicles(
    first: 25
    orderBy: blockTimestamp
    orderDirection: desc
    where: { partner: $partner }
  ) {
    id
    partner
    vin
    displayName
    blockNumber
    blockTimestamp
    transactionHash
  }
}