# .graphclientrc.yml
sources:
  - name: RoboshareProtocol
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/roboshare/protocol
documents:
  - ./graphql/GetVehicles.gql
  - ./graphql/GetAllVehicles.gql
  - ./graphql/GetMarketListings.gql
